import { storeMessage } from "../../util/database.js";
import { WebSocket } from "ws";

export class Room {
  private chatId: number;
  private onlineMemberList: {ws: WebSocket, keyExchangeId: number}[];

  constructor(chatId: number) {
    this.chatId = chatId;
    this.onlineMemberList = [];
  }

  getUser(ws: WebSocket) {
    return this.onlineMemberList.find((val) => val.ws === ws);
  }

  addUser(ws: WebSocket, keyExchangeId: number) {
    this.onlineMemberList.push({ws: ws, keyExchangeId: keyExchangeId});
  }

  removeUser(socket: WebSocket) {
    let userIndex = this.onlineMemberList.findIndex((val) => val.ws === socket);
    if(userIndex >= 0) {
      this.onlineMemberList.splice(userIndex, 1);
    }
  }

  sendMessage(data: ArrayBuffer, sender: WebSocket) {
    const senderData = this.getUser(sender);
    if(!senderData) {
      console.log("User not found!");
      this.removeUser(sender);
      return;
    }

    //generate UUID server-side for message so that client can 
    //state what was the last message they have read. Then use id
    //of message to sort messages from oldest to newest and only retrive
    //messages after a certain message.

    let uuid = crypto.randomUUID(); //v4 UUID is 36 characters long and consists only of 0-9, a-f, A-F, and hyphens(-)

    let dataBase64 = Buffer.from(data).toString('base64');

    //store encrypted message in database for other users.
    //Make sure this does not block main thread by avoiding "await"
    storeMessage(dataBase64, this.chatId, senderData.keyExchangeId, uuid).then((val) => {
      if(val) {
        console.log("Message saved!")
      } else {
        console.warn("Message failed to save!")
      }
    }).catch(e => {
      console.error(e);
    });

    let bufferData = Buffer.from(data);
    let binaryUUID = Buffer.from(uuid, 'utf-8');
    let totalLength = bufferData.length + binaryUUID.length;
    let concatData = Buffer.concat([bufferData, binaryUUID], totalLength);

    for(let member of this.onlineMemberList) {
      if(sender !== member.ws) {
        member.ws.send(concatData, {binary: true});
      }
    }

    //send UUID of message generated by server back to sender
    sender.send(JSON.stringify({type: 'messageConfirm', uuid: uuid}));
    
  }
}